### ISSUE TITLE
Limit reordering to certain indexPaths

### ISSUE THREAD

**Issue by richardvenneman** [bvogelzang/BVReorderTableView#6]
Hi,

Thanks for the great component.

In my previous reordering implementation (with the built-in canMoveRowAtIndexPath) I was able to utilize the `tableView:targetIndexPathForMoveFromRowAtIndexPath:toProposedIndexPath:` method from the UITableViewDelegate and limit the indexPaths to which a row could be moved. It seems that the BVReorderTableView does not support the UITableViewDelegate protocol. Do you have any plans on supporting aforementioned method?

**Comment by addoshi** [comment]
Adding support for the UITableViewDataSource method `- (BOOL)tableView:(UITableView *)tableView canMoveRowAtIndexPath:(NSIndexPath *)indexPath` would be a great improvement for the component.
